image: Visual Studio 2019

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1 --target=CI

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- 'tools -> build.ps1, Source/Cake.Recipe/Content/addins.cake, Source/Cake.Recipe/Content/tools.cake'

#---------------------------------#
#  Environment Variables          #
#---------------------------------#

environment:
  MYGET_SOURCE: